spring.application.name=Ejercicio_tres
spring.ldap.embedded.ldif=classpath:test-server.ldif
# ACTUALIZADO: El nuevo dominio base
spring.ldap.embedded.base-dn=dc=example,dc=com
spring.ldap.embedded.port=8389
spring.ldap.embedded.validation.enabled=false