# ===============================
# = GLOBAL CONFIG
# ===============================
spring.application.name=${SPRING_APP_NAME:DIP_SPRING_SECURITY}
server.port=${SERVER_PORT:8090}
#spring.security.user.name=${SECURITY_USERNAME:jonathan}
#spring.security.user.password=${SECURITY_PASSWORD:1234}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

spring.ldap.embedded.ldif=${SPRING_LDAP_LDIF:classpath:ldap-data.ldif}
spring.ldap.embedded.base-dn=${SPRING_LDAP_BASE_DN:dc=springframework,dc=org}
spring.ldap.embedded.port=${SPRING_LDAP_PORT:8389}
